export const CREATE_HERITAGE = 'create-heritage'
export const EDIT_HERITAGE = 'edit-heritage'
export const DELETE_HERITAGE = 'delete-heritage'
export const QUERY_HERITAGES = 'query-heritages'
export const QUERY_HERITAGE = 'query-heritage'
export const QUERY_USER = 'query-user'
